services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: arabic_agent_app
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app
    environment:
      -  MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      -  MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}  
    env_file:
      - ../src/.env 

    