services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: arabic_agent_app
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app
    env_file:
      - ../src/.env